### ISSUE TITLE
Invalid Jarfile

### ISSUE THREAD

**Issue by wildpalms** [SirBlobman/SirBlobmanAPI#21]
sorry if this is a noob mistake on my behalf.

I add the SirBlobmanCore-2.3.4.jar file in my plugins directory and ran java -jar SirBlobmanCore-2.3.4.jar but I got this result:

Error: Invalid or corrupt jarfile SirBlobmanCore-2.3.4.jar

Is the command I used the correct one to install that file?
I am on Oracle-Linux

**Comment by wildpalms** [comment]
I add the SirBlobmanCore-2.3.4.jar file in my plugins directory and ran` java -jar SirBlobmanCore-2.3.4.jar` but I got this result: 

> Error: Invalid or corrupt jarfile SirBlobmanCore-2.3.4.jar

Is the command I used the correct one to install that file?
I am on Oracle-Linux

**Comment by SirBlobman** [comment]
SirBlobmanCore is not a server jar and cannot be executed.
